### ISSUE TITLE
syntax error in core.py

### ISSUE THREAD

**Issue by LodeVanB** [tvytlx/render-py#7]
python setup.py build_ext --inplace && python try.py
running build_ext
Traceback (most recent call last):
  File "try.py", line 1, in <module>
    from render import render, Model
  File "/home/loderunner-z/render-py/render/__init__.py", line 2, in <module>
    from .core import render
  File "/home/loderunner-z/render-py/render/core.py", line 27
    return f"Vec2d({self.x}, {self.y} )"
                                                     ^
SyntaxError: invalid syntax

**Comment by tvytlx** [comment]
need python version >= 3.6
